services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
  

  prometheus: 
   image: prom/prometheus
   container_name: prometheus
   ports:
    - "9090:9090"
   volumes:
    - "/home/ec2-user/prometheus/:/etc/prometheus/"


  